# Generated by Django 5.0.14 on 2026-03-22 09:15

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscription_active'),
    ]

    operations = []
