# Generated by Django 5.0.14 on 2026-04-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0018_usersubscription_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='user_cancel',
            field=models.BooleanField(default=False),
        ),
    ]
