# Generated by Django 5.0.14 on 2026-03-19 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageVists',
            new_name='PageVisits',
        ),
    ]
