name: Hello World Github Actions

on:
  workflow_dispatch: # Manually trigger the workflow
  # schedule: # Schedule the workflow to run at specific times
  #   - cron: '0 0 * * *' # Runs every day at midnight
  # push: # git push
  #   branches:
  #     - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello there
        run: echo "Hello world!"